### PR TITLE
Test for flock

### PR DESCRIPTION
**Pull request by thrix**
Signed-off-by: Miroslav Vadkerti <mvadkert@redhat.com>

### CODE REVIEW

**Comment by TomasTomecek** [comment]
This is weird. It works just fine for me locally.

**Comment by mrc0mmand** [comment]
As for the current fail during `meson test`, I'd just drop the `check` phase from the specfile, at least for know, so we can concentrate on the rest of the pipeline. Looks like https://github.com/systemd/systemd/issues/11505 but I'm not sure what's going on in there.

**Pull request merged**
