### PR TITLE
Test after upstream sync

### PR DESCRIPTION
**Pull request by mrc0mmand**

### CODE REVIEW

**Comment by lachmanfrantisek** [comment]
Hmm, no builts on copr side:
- prod: https://copr.fedorainfracloud.org/coprs/packit/packit-service-systemd-rhel8-flock-9/builds/
- stg: https://copr.fedorainfracloud.org/coprs/packit/packit-service-systemd-rhel8-flock-9-stg/builds/

In the logs, there is only the error about `utf`.

**Comment by dhodovsk** [comment]
It fails during `packit srpm` (can be reproduced via CLI), when applying one of the patches:
```
Running command ['git', 'diff', '--patch', 'bf61b05a0672de6daf2bfdf2d7f7140f941badef', 'c90c39ff7bf2112616813f609bee4443ae8a715c', '--', '.', ':(exclude)/tmp/systemd-rhel8-flock/packaging/rpm/systemd.spec']
ERROR    'utf-8' codec can't decode byte 0xff in position 902: invalid start byte
```

**Comment by mrc0mmand** [comment]
Is there anything from our side which can be done to fix this?

**Comment by TomasTomecek** [comment]
so there's a unicode character in the patch? well, that needs to be fixed in packit

**Comment by psss** [comment]
@TomasTomecek, shall we file a new packit issue for that? Or do you have enough information to investigate? This is blocking systemd onboarding so it would be nice to have fixed soon. Thanks.

**Comment by TomasTomecek** [comment]
Oki, will take a look.

**Comment by TomasTomecek** [comment]
now it fails on fact that the patches couldn't be applied

**Comment by psss** [comment]
@TomasTomecek, thanks for fixing the encoding issue. @mrc0mmand, could you have a look at the patches?

    + /usr/bin/patch -p1 -s --fuzz=0 --no-backup-if-mismatch
    + /usr/bin/cat /builddir/build/SOURCES/0001-ca8ba8f8c066a47f5c9d033b291f0d6720c658cd.patch
    3 out of 3 hunks FAILED -- saving rejects to file po/pl.po.rej

Thanks.

**Comment by mrc0mmand** [comment]
Well, I think I know where the issue is, but as the current logs make it pretty much a blackbox, I can only assume.

I'm not entirely sure how the patches are generated, but as you use git, you apparently generate them using git as well by `git format-patch` or otherwise. However, according to the logs, the patch application process is done via the `patch` utility:

```
+ cd systemd-rhel8-flock-efb536d0cbe2e58f80e501d19999928c75e08f6a
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ /usr/bin/cat /builddir/build/SOURCES/0001-ca8ba8f8c066a47f5c9d033b291f0d6720c658cd.patch
+ /usr/bin/patch -p1 -s --fuzz=0 --no-backup-if-mismatch
+ /usr/bin/cat /builddir/build/SOURCES/0002-f7f9c69ac58748e37629015ab288d40b1966ac88.patch
```

and that's clearly wrong, as it can (and quite possibly even does) break certain patches, like binary-only patches, etc. This should be fixed by `%autosetup -S git` or more preferably `%autosetup -S git_am` in the spec.

Once again, all this is just one big assumption, as the logs don't provide much insight into the generated files, but since the patches are definitely correct (otherwise they wouldn't be in the `master` branch in the first place), the issue must be somewhere else.

**Comment by TomasTomecek** [comment]
@mrc0mmand https://github.com/packit-service/packit/issues/639 opened an issue tracking this problem

**Comment by TomasTomecek** [comment]
pushed changes which should make this PR buildable again, once we update production packit-service

**Comment by TomasTomecek** [comment]
my bad, forgot to push the new tag

**Comment by TomasTomecek** [comment]
let's try again

**Comment by psss** [comment]
Source rpm built successfully. Now the problem appears during copr build. @mrc0mmand, is this on the side of systemd/spec file or does it look like another packit issue?

**Comment by lachmanfrantisek** [comment]
> Source rpm built successfully. Now the problem appears during copr build. @mrc0mmand, is this on the side of systemd/spec file or does it look like another packit issue?

@psss We have currently some problems with the packit-service. (The fix/revert should be ready soon.)

**Comment by TomasTomecek** [comment]
The build failures seem to indicate that systemd doesn't build with fedora meson so... We certainly can't help with that.

**Pull request closed without merging**
